FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY consenso1 ./
RUN go build -o consenso1 consenso1.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/consenso1 ./

CMD ["./consenso1"]