FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY MR3 ./
RUN go build -o MR3 MR3.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/MR3 ./

CMD ["./MR3"]