FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY cordinador ./
RUN go build -o cordinador cordinador.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/cordinador ./

CMD ["./cordinador"]