FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY coordinador ./coordinador
RUN go build -o coordinador ./coordinador/coordinador.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/coordinador ./

CMD ["./coordinador"]