FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY broker ./
RUN go build -o broker .

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/broker .
CMD ["./broker"]