FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY RYW1 ./RYW1
RUN go build -o ryw1 ./RYW1/RYW1.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/ryw1 .
CMD ["./ryw1"]