FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY RYW2 ./
RUN go build -o RYW2 .

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/RYW2 .
CMD ["./RYW2"]