FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY datanode3 ./
RUN go build -o datanode3 datanode3.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/datanode3 ./

CMD ["./datanode3"]