FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY RYW3 ./
RUN go build -o RYW3 .

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/RYW3 .
CMD ["./RYW3"]