FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY MR2 ./
RUN go build -o MR2 MR2.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/MR2 ./

CMD ["./MR2"]