FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY datanode1 ./
RUN go build -o datanode1 datanode1.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/datanode1 ./

CMD ["./datanode1"]