// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/greeter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type AsientoSelect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsientoID     string                 `protobuf:"bytes,1,opt,name=asientoID,proto3" json:"asientoID,omitempty"`
	Asiento       string                 `protobuf:"bytes,2,opt,name=asiento,proto3" json:"asiento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsientoSelect) Reset() {
	*x = AsientoSelect{}
	mi := &file_proto_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsientoSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsientoSelect) ProtoMessage() {}

func (x *AsientoSelect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsientoSelect.ProtoReflect.Descriptor instead.
func (*AsientoSelect) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *AsientoSelect) GetAsientoID() string {
	if x != nil {
		return x.AsientoID
	}
	return ""
}

func (x *AsientoSelect) GetAsiento() string {
	if x != nil {
		return x.Asiento
	}
	return ""
}

type FactBaggage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaggageID     string                 `protobuf:"bytes,1,opt,name=BaggageID,proto3" json:"BaggageID,omitempty"`
	Baggage       string                 `protobuf:"bytes,2,opt,name=Baggage,proto3" json:"Baggage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactBaggage) Reset() {
	*x = FactBaggage{}
	mi := &file_proto_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactBaggage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactBaggage) ProtoMessage() {}

func (x *FactBaggage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactBaggage.ProtoReflect.Descriptor instead.
func (*FactBaggage) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *FactBaggage) GetBaggageID() string {
	if x != nil {
		return x.BaggageID
	}
	return ""
}

func (x *FactBaggage) GetBaggage() string {
	if x != nil {
		return x.Baggage
	}
	return ""
}

type SolicitudEstado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cliente       string                 `protobuf:"bytes,1,opt,name=cliente,proto3" json:"cliente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudEstado) Reset() {
	*x = SolicitudEstado{}
	mi := &file_proto_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudEstado) ProtoMessage() {}

func (x *SolicitudEstado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudEstado.ProtoReflect.Descriptor instead.
func (*SolicitudEstado) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *SolicitudEstado) GetCliente() string {
	if x != nil {
		return x.Cliente
	}
	return ""
}

type RequestAsignar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cliente       string                 `protobuf:"bytes,1,opt,name=cliente,proto3" json:"cliente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAsignar) Reset() {
	*x = RequestAsignar{}
	mi := &file_proto_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAsignar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAsignar) ProtoMessage() {}

func (x *RequestAsignar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAsignar.ProtoReflect.Descriptor instead.
func (*RequestAsignar) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *RequestAsignar) GetCliente() string {
	if x != nil {
		return x.Cliente
	}
	return ""
}

type ResponseAsignar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datanode      string                 `protobuf:"bytes,1,opt,name=datanode,proto3" json:"datanode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseAsignar) Reset() {
	*x = ResponseAsignar{}
	mi := &file_proto_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAsignar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAsignar) ProtoMessage() {}

func (x *ResponseAsignar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAsignar.ProtoReflect.Descriptor instead.
func (*ResponseAsignar) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseAsignar) GetDatanode() string {
	if x != nil {
		return x.Datanode
	}
	return ""
}

type ResponseEstadoAsignado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datanode      string                 `protobuf:"bytes,1,opt,name=datanode,proto3" json:"datanode,omitempty"`
	IdSistema     string                 `protobuf:"bytes,2,opt,name=idSistema,proto3" json:"idSistema,omitempty"`
	Asientos      map[string]bool        `protobuf:"bytes,3,rep,name=asientos,proto3" json:"asientos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseEstadoAsignado) Reset() {
	*x = ResponseEstadoAsignado{}
	mi := &file_proto_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEstadoAsignado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEstadoAsignado) ProtoMessage() {}

func (x *ResponseEstadoAsignado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEstadoAsignado.ProtoReflect.Descriptor instead.
func (*ResponseEstadoAsignado) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseEstadoAsignado) GetDatanode() string {
	if x != nil {
		return x.Datanode
	}
	return ""
}

func (x *ResponseEstadoAsignado) GetIdSistema() string {
	if x != nil {
		return x.IdSistema
	}
	return ""
}

func (x *ResponseEstadoAsignado) GetAsientos() map[string]bool {
	if x != nil {
		return x.Asientos
	}
	return nil
}

type Estado struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AsientosDisponibles map[string]bool        `protobuf:"bytes,2,rep,name=asientos_disponibles,json=asientosDisponibles,proto3" json:"asientos_disponibles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Estado) Reset() {
	*x = Estado{}
	mi := &file_proto_greeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{7}
}

func (x *Estado) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Estado) GetAsientosDisponibles() map[string]bool {
	if x != nil {
		return x.AsientosDisponibles
	}
	return nil
}

var File_proto_greeter_proto protoreflect.FileDescriptor

const file_proto_greeter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/greeter.proto\x12\x05heint\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"G\n" +
	"\rAsientoSelect\x12\x1c\n" +
	"\tasientoID\x18\x01 \x01(\tR\tasientoID\x12\x18\n" +
	"\aasiento\x18\x02 \x01(\tR\aasiento\"E\n" +
	"\vFactBaggage\x12\x1c\n" +
	"\tBaggageID\x18\x01 \x01(\tR\tBaggageID\x12\x18\n" +
	"\aBaggage\x18\x02 \x01(\tR\aBaggage\"+\n" +
	"\x0fSolicitudEstado\x12\x18\n" +
	"\acliente\x18\x01 \x01(\tR\acliente\"*\n" +
	"\x0eRequestAsignar\x12\x18\n" +
	"\acliente\x18\x01 \x01(\tR\acliente\"-\n" +
	"\x0fResponseAsignar\x12\x1a\n" +
	"\bdatanode\x18\x01 \x01(\tR\bdatanode\"\xd8\x01\n" +
	"\x16ResponseEstadoAsignado\x12\x1a\n" +
	"\bdatanode\x18\x01 \x01(\tR\bdatanode\x12\x1c\n" +
	"\tidSistema\x18\x02 \x01(\tR\tidSistema\x12G\n" +
	"\basientos\x18\x03 \x03(\v2+.heint.ResponseEstadoAsignado.AsientosEntryR\basientos\x1a;\n" +
	"\rAsientosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x06Estado\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12Y\n" +
	"\x14asientos_disponibles\x18\x02 \x03(\v2&.heint.Estado.AsientosDisponiblesEntryR\x13asientosDisponibles\x1aF\n" +
	"\x18AsientosDisponiblesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xa9\x02\n" +
	"\rBrokerService\x12-\n" +
	"\tSendOffer\x12\x0f.heint.Response\x1a\x0f.heint.Response\x12,\n" +
	"\n" +
	"SendEstado\x12\x0f.heint.Response\x1a\r.heint.Estado\x124\n" +
	"\vSendReserva\x12\x14.heint.AsientoSelect\x1a\x0f.heint.Response\x122\n" +
	"\vSendBaggage\x12\x12.heint.FactBaggage\x1a\x0f.heint.Response\x12Q\n" +
	"\x18ObtenerEstadoYAsignacion\x12\x16.heint.SolicitudEstado\x1a\x1d.heint.ResponseEstadoAsignado2\x93\x01\n" +
	"\x0fDataNodeService\x12F\n" +
	"\rObtenerEstado\x12\x16.heint.SolicitudEstado\x1a\x1d.heint.ResponseEstadoAsignado\x128\n" +
	"\x0fEscribirReserva\x12\x14.heint.AsientoSelect\x1a\x0f.heint.Response2\xa7\x01\n" +
	"\x10AsignadorService\x12@\n" +
	"\x0fAsignarDataNode\x12\x15.heint.RequestAsignar\x1a\x16.heint.ResponseAsignar\x12Q\n" +
	"\x18ObtenerEstadoYAsignacion\x12\x16.heint.SolicitudEstado\x1a\x1d.heint.ResponseEstadoAsignadoB\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_greeter_proto_rawDescOnce sync.Once
	file_proto_greeter_proto_rawDescData []byte
)

func file_proto_greeter_proto_rawDescGZIP() []byte {
	file_proto_greeter_proto_rawDescOnce.Do(func() {
		file_proto_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greeter_proto_rawDesc), len(file_proto_greeter_proto_rawDesc)))
	})
	return file_proto_greeter_proto_rawDescData
}

var file_proto_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_greeter_proto_goTypes = []any{
	(*Response)(nil),               // 0: heint.Response
	(*AsientoSelect)(nil),          // 1: heint.AsientoSelect
	(*FactBaggage)(nil),            // 2: heint.FactBaggage
	(*SolicitudEstado)(nil),        // 3: heint.SolicitudEstado
	(*RequestAsignar)(nil),         // 4: heint.RequestAsignar
	(*ResponseAsignar)(nil),        // 5: heint.ResponseAsignar
	(*ResponseEstadoAsignado)(nil), // 6: heint.ResponseEstadoAsignado
	(*Estado)(nil),                 // 7: heint.Estado
	nil,                            // 8: heint.ResponseEstadoAsignado.AsientosEntry
	nil,                            // 9: heint.Estado.AsientosDisponiblesEntry
}
var file_proto_greeter_proto_depIdxs = []int32{
	8,  // 0: heint.ResponseEstadoAsignado.asientos:type_name -> heint.ResponseEstadoAsignado.AsientosEntry
	9,  // 1: heint.Estado.asientos_disponibles:type_name -> heint.Estado.AsientosDisponiblesEntry
	0,  // 2: heint.BrokerService.SendOffer:input_type -> heint.Response
	0,  // 3: heint.BrokerService.SendEstado:input_type -> heint.Response
	1,  // 4: heint.BrokerService.SendReserva:input_type -> heint.AsientoSelect
	2,  // 5: heint.BrokerService.SendBaggage:input_type -> heint.FactBaggage
	3,  // 6: heint.BrokerService.ObtenerEstadoYAsignacion:input_type -> heint.SolicitudEstado
	3,  // 7: heint.DataNodeService.ObtenerEstado:input_type -> heint.SolicitudEstado
	1,  // 8: heint.DataNodeService.EscribirReserva:input_type -> heint.AsientoSelect
	4,  // 9: heint.AsignadorService.AsignarDataNode:input_type -> heint.RequestAsignar
	3,  // 10: heint.AsignadorService.ObtenerEstadoYAsignacion:input_type -> heint.SolicitudEstado
	0,  // 11: heint.BrokerService.SendOffer:output_type -> heint.Response
	7,  // 12: heint.BrokerService.SendEstado:output_type -> heint.Estado
	0,  // 13: heint.BrokerService.SendReserva:output_type -> heint.Response
	0,  // 14: heint.BrokerService.SendBaggage:output_type -> heint.Response
	6,  // 15: heint.BrokerService.ObtenerEstadoYAsignacion:output_type -> heint.ResponseEstadoAsignado
	6,  // 16: heint.DataNodeService.ObtenerEstado:output_type -> heint.ResponseEstadoAsignado
	0,  // 17: heint.DataNodeService.EscribirReserva:output_type -> heint.Response
	5,  // 18: heint.AsignadorService.AsignarDataNode:output_type -> heint.ResponseAsignar
	6,  // 19: heint.AsignadorService.ObtenerEstadoYAsignacion:output_type -> heint.ResponseEstadoAsignado
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_greeter_proto_init() }
func file_proto_greeter_proto_init() {
	if File_proto_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greeter_proto_rawDesc), len(file_proto_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_greeter_proto_goTypes,
		DependencyIndexes: file_proto_greeter_proto_depIdxs,
		MessageInfos:      file_proto_greeter_proto_msgTypes,
	}.Build()
	File_proto_greeter_proto = out.File
	file_proto_greeter_proto_goTypes = nil
	file_proto_greeter_proto_depIdxs = nil
}
