// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/greeter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type AsientoSelect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsientoID     string                 `protobuf:"bytes,1,opt,name=asientoID,proto3" json:"asientoID,omitempty"`
	Asiento       string                 `protobuf:"bytes,2,opt,name=asiento,proto3" json:"asiento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsientoSelect) Reset() {
	*x = AsientoSelect{}
	mi := &file_proto_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsientoSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsientoSelect) ProtoMessage() {}

func (x *AsientoSelect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsientoSelect.ProtoReflect.Descriptor instead.
func (*AsientoSelect) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *AsientoSelect) GetAsientoID() string {
	if x != nil {
		return x.AsientoID
	}
	return ""
}

func (x *AsientoSelect) GetAsiento() string {
	if x != nil {
		return x.Asiento
	}
	return ""
}

type FactBaggage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaggageID     string                 `protobuf:"bytes,1,opt,name=BaggageID,proto3" json:"BaggageID,omitempty"`
	Baggage       string                 `protobuf:"bytes,2,opt,name=Baggage,proto3" json:"Baggage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactBaggage) Reset() {
	*x = FactBaggage{}
	mi := &file_proto_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactBaggage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactBaggage) ProtoMessage() {}

func (x *FactBaggage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactBaggage.ProtoReflect.Descriptor instead.
func (*FactBaggage) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *FactBaggage) GetBaggageID() string {
	if x != nil {
		return x.BaggageID
	}
	return ""
}

func (x *FactBaggage) GetBaggage() string {
	if x != nil {
		return x.Baggage
	}
	return ""
}

type SolicitudEstado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cliente       string                 `protobuf:"bytes,1,opt,name=cliente,proto3" json:"cliente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudEstado) Reset() {
	*x = SolicitudEstado{}
	mi := &file_proto_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudEstado) ProtoMessage() {}

func (x *SolicitudEstado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudEstado.ProtoReflect.Descriptor instead.
func (*SolicitudEstado) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *SolicitudEstado) GetCliente() string {
	if x != nil {
		return x.Cliente
	}
	return ""
}

type RequestAsignar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cliente       string                 `protobuf:"bytes,1,opt,name=cliente,proto3" json:"cliente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAsignar) Reset() {
	*x = RequestAsignar{}
	mi := &file_proto_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAsignar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAsignar) ProtoMessage() {}

func (x *RequestAsignar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAsignar.ProtoReflect.Descriptor instead.
func (*RequestAsignar) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *RequestAsignar) GetCliente() string {
	if x != nil {
		return x.Cliente
	}
	return ""
}

type ResponseAsignar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datanode      string                 `protobuf:"bytes,1,opt,name=datanode,proto3" json:"datanode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseAsignar) Reset() {
	*x = ResponseAsignar{}
	mi := &file_proto_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAsignar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAsignar) ProtoMessage() {}

func (x *ResponseAsignar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAsignar.ProtoReflect.Descriptor instead.
func (*ResponseAsignar) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseAsignar) GetDatanode() string {
	if x != nil {
		return x.Datanode
	}
	return ""
}

type ResponseEstadoAsignado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datanode      string                 `protobuf:"bytes,1,opt,name=datanode,proto3" json:"datanode,omitempty"`
	IdSistema     string                 `protobuf:"bytes,2,opt,name=idSistema,proto3" json:"idSistema,omitempty"`
	Asientos      map[string]bool        `protobuf:"bytes,3,rep,name=asientos,proto3" json:"asientos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseEstadoAsignado) Reset() {
	*x = ResponseEstadoAsignado{}
	mi := &file_proto_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEstadoAsignado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEstadoAsignado) ProtoMessage() {}

func (x *ResponseEstadoAsignado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEstadoAsignado.ProtoReflect.Descriptor instead.
func (*ResponseEstadoAsignado) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseEstadoAsignado) GetDatanode() string {
	if x != nil {
		return x.Datanode
	}
	return ""
}

func (x *ResponseEstadoAsignado) GetIdSistema() string {
	if x != nil {
		return x.IdSistema
	}
	return ""
}

func (x *ResponseEstadoAsignado) GetAsientos() map[string]bool {
	if x != nil {
		return x.Asientos
	}
	return nil
}

type Estado struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AsientosDisponibles map[string]bool        `protobuf:"bytes,2,rep,name=asientos_disponibles,json=asientosDisponibles,proto3" json:"asientos_disponibles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Estado) Reset() {
	*x = Estado{}
	mi := &file_proto_greeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{7}
}

func (x *Estado) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Estado) GetAsientosDisponibles() map[string]bool {
	if x != nil {
		return x.AsientosDisponibles
	}
	return nil
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  int32                  `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int32                  `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_proto_greeter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{8}
}

func (x *VoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *VoteRequest) GetLastLogIndex() int32 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *VoteRequest) GetLastLogTerm() int32 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_proto_greeter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{9}
}

func (x *VoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_greeter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  int32                  `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   int32                  `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int32                  `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_proto_greeter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{11}
}

func (x *AppendRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendRequest) GetPrevLogIndex() int32 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendRequest) GetPrevLogTerm() int32 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendRequest) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	MatchIndex    int32                  `protobuf:"varint,3,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_proto_greeter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{12}
}

func (x *AppendResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendResponse) GetMatchIndex() int32 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_proto_greeter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{13}
}

func (x *Proposal) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ConsensusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusReply) Reset() {
	*x = ConsensusReply{}
	mi := &file_proto_greeter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusReply) ProtoMessage() {}

func (x *ConsensusReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusReply.ProtoReflect.Descriptor instead.
func (*ConsensusReply) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{14}
}

func (x *ConsensusReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsensusReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	LastVersion   int64                  `protobuf:"varint,2,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightRequest) Reset() {
	*x = FlightRequest{}
	mi := &file_proto_greeter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightRequest) ProtoMessage() {}

func (x *FlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightRequest.ProtoReflect.Descriptor instead.
func (*FlightRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{15}
}

func (x *FlightRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FlightRequest) GetLastVersion() int64 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

type FlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightResponse) Reset() {
	*x = FlightResponse{}
	mi := &file_proto_greeter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightResponse) ProtoMessage() {}

func (x *FlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightResponse.ProtoReflect.Descriptor instead.
func (*FlightResponse) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{16}
}

func (x *FlightResponse) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FlightResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FlightResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_proto_greeter_proto protoreflect.FileDescriptor

const file_proto_greeter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/greeter.proto\x12\x05heint\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"G\n" +
	"\rAsientoSelect\x12\x1c\n" +
	"\tasientoID\x18\x01 \x01(\tR\tasientoID\x12\x18\n" +
	"\aasiento\x18\x02 \x01(\tR\aasiento\"E\n" +
	"\vFactBaggage\x12\x1c\n" +
	"\tBaggageID\x18\x01 \x01(\tR\tBaggageID\x12\x18\n" +
	"\aBaggage\x18\x02 \x01(\tR\aBaggage\"+\n" +
	"\x0fSolicitudEstado\x12\x18\n" +
	"\acliente\x18\x01 \x01(\tR\acliente\"*\n" +
	"\x0eRequestAsignar\x12\x18\n" +
	"\acliente\x18\x01 \x01(\tR\acliente\"-\n" +
	"\x0fResponseAsignar\x12\x1a\n" +
	"\bdatanode\x18\x01 \x01(\tR\bdatanode\"\xd8\x01\n" +
	"\x16ResponseEstadoAsignado\x12\x1a\n" +
	"\bdatanode\x18\x01 \x01(\tR\bdatanode\x12\x1c\n" +
	"\tidSistema\x18\x02 \x01(\tR\tidSistema\x12G\n" +
	"\basientos\x18\x03 \x03(\v2+.heint.ResponseEstadoAsignado.AsientosEntryR\basientos\x1a;\n" +
	"\rAsientosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x06Estado\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12Y\n" +
	"\x14asientos_disponibles\x18\x02 \x03(\v2&.heint.Estado.AsientosDisponiblesEntryR\x13asientosDisponibles\x1aF\n" +
	"\x18AsientosDisponiblesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x8e\x01\n" +
	"\vVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x05R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x05R\vlastLogTerm\"E\n" +
	"\fVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"8\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\xda\x01\n" +
	"\rAppendRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x05R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x05R\vprevLogTerm\x12)\n" +
	"\aentries\x18\x05 \x03(\v2\x0f.heint.LogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x05R\fleaderCommit\"_\n" +
	"\x0eAppendResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vmatch_index\x18\x03 \x01(\x05R\n" +
	"matchIndex\"$\n" +
	"\bProposal\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"B\n" +
	"\x0eConsensusReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"O\n" +
	"\rFlightRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12!\n" +
	"\flast_version\x18\x02 \x01(\x03R\vlastVersion\"]\n" +
	"\x0eFlightResponse\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state2\xa9\x02\n" +
	"\rBrokerService\x12-\n" +
	"\tSendOffer\x12\x0f.heint.Response\x1a\x0f.heint.Response\x12,\n" +
	"\n" +
	"SendEstado\x12\x0f.heint.Response\x1a\r.heint.Estado\x124\n" +
	"\vSendReserva\x12\x14.heint.AsientoSelect\x1a\x0f.heint.Response\x122\n" +
	"\vSendBaggage\x12\x12.heint.FactBaggage\x1a\x0f.heint.Response\x12Q\n" +
	"\x18ObtenerEstadoYAsignacion\x12\x16.heint.SolicitudEstado\x1a\x1d.heint.ResponseEstadoAsignado2\x93\x01\n" +
	"\x0fDataNodeService\x12F\n" +
	"\rObtenerEstado\x12\x16.heint.SolicitudEstado\x1a\x1d.heint.ResponseEstadoAsignado\x128\n" +
	"\x0fEscribirReserva\x12\x14.heint.AsientoSelect\x1a\x0f.heint.Response2\xa7\x01\n" +
	"\x10AsignadorService\x12@\n" +
	"\x0fAsignarDataNode\x12\x15.heint.RequestAsignar\x1a\x16.heint.ResponseAsignar\x12Q\n" +
	"\x18ObtenerEstadoYAsignacion\x12\x16.heint.SolicitudEstado\x1a\x1d.heint.ResponseEstadoAsignado2\xba\x01\n" +
	"\tConsensus\x128\n" +
	"\vRequestVote\x12\x12.heint.VoteRequest\x1a\x13.heint.VoteResponse\"\x00\x12>\n" +
	"\rAppendEntries\x12\x14.heint.AppendRequest\x1a\x15.heint.AppendResponse\"\x00\x123\n" +
	"\aPropose\x12\x0f.heint.Proposal\x1a\x15.heint.ConsensusReply\"\x002O\n" +
	"\vInfoService\x12@\n" +
	"\x0fGetFlightStatus\x12\x14.heint.FlightRequest\x1a\x15.heint.FlightResponse\"\x00B\x0eZ\f/proto;protob\x06proto3"

var (
	file_proto_greeter_proto_rawDescOnce sync.Once
	file_proto_greeter_proto_rawDescData []byte
)

func file_proto_greeter_proto_rawDescGZIP() []byte {
	file_proto_greeter_proto_rawDescOnce.Do(func() {
		file_proto_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greeter_proto_rawDesc), len(file_proto_greeter_proto_rawDesc)))
	})
	return file_proto_greeter_proto_rawDescData
}

var file_proto_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_greeter_proto_goTypes = []any{
	(*Response)(nil),               // 0: heint.Response
	(*AsientoSelect)(nil),          // 1: heint.AsientoSelect
	(*FactBaggage)(nil),            // 2: heint.FactBaggage
	(*SolicitudEstado)(nil),        // 3: heint.SolicitudEstado
	(*RequestAsignar)(nil),         // 4: heint.RequestAsignar
	(*ResponseAsignar)(nil),        // 5: heint.ResponseAsignar
	(*ResponseEstadoAsignado)(nil), // 6: heint.ResponseEstadoAsignado
	(*Estado)(nil),                 // 7: heint.Estado
	(*VoteRequest)(nil),            // 8: heint.VoteRequest
	(*VoteResponse)(nil),           // 9: heint.VoteResponse
	(*LogEntry)(nil),               // 10: heint.LogEntry
	(*AppendRequest)(nil),          // 11: heint.AppendRequest
	(*AppendResponse)(nil),         // 12: heint.AppendResponse
	(*Proposal)(nil),               // 13: heint.Proposal
	(*ConsensusReply)(nil),         // 14: heint.ConsensusReply
	(*FlightRequest)(nil),          // 15: heint.FlightRequest
	(*FlightResponse)(nil),         // 16: heint.FlightResponse
	nil,                            // 17: heint.ResponseEstadoAsignado.AsientosEntry
	nil,                            // 18: heint.Estado.AsientosDisponiblesEntry
}
var file_proto_greeter_proto_depIdxs = []int32{
	17, // 0: heint.ResponseEstadoAsignado.asientos:type_name -> heint.ResponseEstadoAsignado.AsientosEntry
	18, // 1: heint.Estado.asientos_disponibles:type_name -> heint.Estado.AsientosDisponiblesEntry
	10, // 2: heint.AppendRequest.entries:type_name -> heint.LogEntry
	0,  // 3: heint.BrokerService.SendOffer:input_type -> heint.Response
	0,  // 4: heint.BrokerService.SendEstado:input_type -> heint.Response
	1,  // 5: heint.BrokerService.SendReserva:input_type -> heint.AsientoSelect
	2,  // 6: heint.BrokerService.SendBaggage:input_type -> heint.FactBaggage
	3,  // 7: heint.BrokerService.ObtenerEstadoYAsignacion:input_type -> heint.SolicitudEstado
	3,  // 8: heint.DataNodeService.ObtenerEstado:input_type -> heint.SolicitudEstado
	1,  // 9: heint.DataNodeService.EscribirReserva:input_type -> heint.AsientoSelect
	4,  // 10: heint.AsignadorService.AsignarDataNode:input_type -> heint.RequestAsignar
	3,  // 11: heint.AsignadorService.ObtenerEstadoYAsignacion:input_type -> heint.SolicitudEstado
	8,  // 12: heint.Consensus.RequestVote:input_type -> heint.VoteRequest
	11, // 13: heint.Consensus.AppendEntries:input_type -> heint.AppendRequest
	13, // 14: heint.Consensus.Propose:input_type -> heint.Proposal
	15, // 15: heint.InfoService.GetFlightStatus:input_type -> heint.FlightRequest
	0,  // 16: heint.BrokerService.SendOffer:output_type -> heint.Response
	7,  // 17: heint.BrokerService.SendEstado:output_type -> heint.Estado
	0,  // 18: heint.BrokerService.SendReserva:output_type -> heint.Response
	0,  // 19: heint.BrokerService.SendBaggage:output_type -> heint.Response
	6,  // 20: heint.BrokerService.ObtenerEstadoYAsignacion:output_type -> heint.ResponseEstadoAsignado
	6,  // 21: heint.DataNodeService.ObtenerEstado:output_type -> heint.ResponseEstadoAsignado
	0,  // 22: heint.DataNodeService.EscribirReserva:output_type -> heint.Response
	5,  // 23: heint.AsignadorService.AsignarDataNode:output_type -> heint.ResponseAsignar
	6,  // 24: heint.AsignadorService.ObtenerEstadoYAsignacion:output_type -> heint.ResponseEstadoAsignado
	9,  // 25: heint.Consensus.RequestVote:output_type -> heint.VoteResponse
	12, // 26: heint.Consensus.AppendEntries:output_type -> heint.AppendResponse
	14, // 27: heint.Consensus.Propose:output_type -> heint.ConsensusReply
	16, // 28: heint.InfoService.GetFlightStatus:output_type -> heint.FlightResponse
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_greeter_proto_init() }
func file_proto_greeter_proto_init() {
	if File_proto_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greeter_proto_rawDesc), len(file_proto_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_greeter_proto_goTypes,
		DependencyIndexes: file_proto_greeter_proto_depIdxs,
		MessageInfos:      file_proto_greeter_proto_msgTypes,
	}.Build()
	File_proto_greeter_proto = out.File
	file_proto_greeter_proto_goTypes = nil
	file_proto_greeter_proto_depIdxs = nil
}
