// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/greeter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfertaId      string                 `protobuf:"bytes,1,opt,name=oferta_id,json=ofertaId,proto3" json:"oferta_id,omitempty"`
	ProductoId    string                 `protobuf:"bytes,2,opt,name=producto_id,json=productoId,proto3" json:"producto_id,omitempty"`
	Tienda        string                 `protobuf:"bytes,3,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Categoria     string                 `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Producto      string                 `protobuf:"bytes,5,opt,name=producto,proto3" json:"producto,omitempty"`
	Precio        float64                `protobuf:"fixed64,6,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Fecha         int64                  `protobuf:"varint,8,opt,name=fecha,proto3" json:"fecha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_proto_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *Offer) GetOfertaId() string {
	if x != nil {
		return x.OfertaId
	}
	return ""
}

func (x *Offer) GetProductoId() string {
	if x != nil {
		return x.ProductoId
	}
	return ""
}

func (x *Offer) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Offer) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Offer) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Offer) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Offer) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Offer) GetFecha() int64 {
	if x != nil {
		return x.Fecha
	}
	return 0
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumidorId  string                 `protobuf:"bytes,1,opt,name=consumidor_id,json=consumidorId,proto3" json:"consumidor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryRequest) GetConsumidorId() string {
	if x != nil {
		return x.ConsumidorId
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Store         string                 `protobuf:"bytes,2,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *RegisterRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumidorId  string                 `protobuf:"bytes,1,opt,name=consumidor_id,json=consumidorId,proto3" json:"consumidor_id,omitempty"`
	Categorias    []string               `protobuf:"bytes,2,rep,name=categorias,proto3" json:"categorias,omitempty"`
	Tiendas       []string               `protobuf:"bytes,3,rep,name=tiendas,proto3" json:"tiendas,omitempty"`
	PrecioMax     float64                `protobuf:"fixed64,4,opt,name=precio_max,json=precioMax,proto3" json:"precio_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_proto_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionRequest) GetConsumidorId() string {
	if x != nil {
		return x.ConsumidorId
	}
	return ""
}

func (x *SubscriptionRequest) GetCategorias() []string {
	if x != nil {
		return x.Categorias
	}
	return nil
}

func (x *SubscriptionRequest) GetTiendas() []string {
	if x != nil {
		return x.Tiendas
	}
	return nil
}

func (x *SubscriptionRequest) GetPrecioMax() float64 {
	if x != nil {
		return x.PrecioMax
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *HistoryResponse) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

var File_proto_greeter_proto protoreflect.FileDescriptor

const file_proto_greeter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/greeter.proto\x12\x05heint\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"\xdb\x01\n" +
	"\x05Offer\x12\x1b\n" +
	"\toferta_id\x18\x01 \x01(\tR\bofertaId\x12\x1f\n" +
	"\vproducto_id\x18\x02 \x01(\tR\n" +
	"productoId\x12\x16\n" +
	"\x06tienda\x18\x03 \x01(\tR\x06tienda\x12\x1c\n" +
	"\tcategoria\x18\x04 \x01(\tR\tcategoria\x12\x1a\n" +
	"\bproducto\x18\x05 \x01(\tR\bproducto\x12\x16\n" +
	"\x06precio\x18\x06 \x01(\x01R\x06precio\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x14\n" +
	"\x05fecha\x18\b \x01(\x03R\x05fecha\"5\n" +
	"\x0eHistoryRequest\x12#\n" +
	"\rconsumidor_id\x18\x01 \x01(\tR\fconsumidorId\"H\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x14\n" +
	"\x05store\x18\x02 \x01(\tR\x05store\"<\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x93\x01\n" +
	"\x13SubscriptionRequest\x12#\n" +
	"\rconsumidor_id\x18\x01 \x01(\tR\fconsumidorId\x12\x1e\n" +
	"\n" +
	"categorias\x18\x02 \x03(\tR\n" +
	"categorias\x12\x18\n" +
	"\atiendas\x18\x03 \x03(\tR\atiendas\x12\x1d\n" +
	"\n" +
	"precio_max\x18\x04 \x01(\x01R\tprecioMax\"7\n" +
	"\x0fHistoryResponse\x12$\n" +
	"\x06offers\x18\x01 \x03(\v2\f.heint.OfferR\x06offers2\xb5\x03\n" +
	"\rBrokerService\x12*\n" +
	"\tSendOffer\x12\f.heint.Offer\x1a\x0f.heint.Response\x12;\n" +
	"\n" +
	"GetHistory\x12\x15.heint.HistoryRequest\x1a\x16.heint.HistoryResponse\x12C\n" +
	"\x10RegisterProducer\x12\x16.heint.RegisterRequest\x1a\x17.heint.RegisterResponse\x121\n" +
	"\x10SendOfferToNodes\x12\f.heint.Offer\x1a\x0f.heint.Response\x12=\n" +
	"\x0fSubscribeOffers\x12\x1a.heint.SubscriptionRequest\x1a\f.heint.Offer0\x01\x12?\n" +
	"\fRegisterNode\x12\x16.heint.RegisterRequest\x1a\x17.heint.RegisterResponse\x12C\n" +
	"\x10RegisterConsumer\x12\x16.heint.RegisterRequest\x1a\x17.heint.RegisterResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_greeter_proto_rawDescOnce sync.Once
	file_proto_greeter_proto_rawDescData []byte
)

func file_proto_greeter_proto_rawDescGZIP() []byte {
	file_proto_greeter_proto_rawDescOnce.Do(func() {
		file_proto_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greeter_proto_rawDesc), len(file_proto_greeter_proto_rawDesc)))
	})
	return file_proto_greeter_proto_rawDescData
}

var file_proto_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_greeter_proto_goTypes = []any{
	(*Response)(nil),            // 0: heint.Response
	(*Offer)(nil),               // 1: heint.Offer
	(*HistoryRequest)(nil),      // 2: heint.HistoryRequest
	(*RegisterRequest)(nil),     // 3: heint.RegisterRequest
	(*RegisterResponse)(nil),    // 4: heint.RegisterResponse
	(*SubscriptionRequest)(nil), // 5: heint.SubscriptionRequest
	(*HistoryResponse)(nil),     // 6: heint.HistoryResponse
}
var file_proto_greeter_proto_depIdxs = []int32{
	1, // 0: heint.HistoryResponse.offers:type_name -> heint.Offer
	1, // 1: heint.BrokerService.SendOffer:input_type -> heint.Offer
	2, // 2: heint.BrokerService.GetHistory:input_type -> heint.HistoryRequest
	3, // 3: heint.BrokerService.RegisterProducer:input_type -> heint.RegisterRequest
	1, // 4: heint.BrokerService.SendOfferToNodes:input_type -> heint.Offer
	5, // 5: heint.BrokerService.SubscribeOffers:input_type -> heint.SubscriptionRequest
	3, // 6: heint.BrokerService.RegisterNode:input_type -> heint.RegisterRequest
	3, // 7: heint.BrokerService.RegisterConsumer:input_type -> heint.RegisterRequest
	0, // 8: heint.BrokerService.SendOffer:output_type -> heint.Response
	6, // 9: heint.BrokerService.GetHistory:output_type -> heint.HistoryResponse
	4, // 10: heint.BrokerService.RegisterProducer:output_type -> heint.RegisterResponse
	0, // 11: heint.BrokerService.SendOfferToNodes:output_type -> heint.Response
	1, // 12: heint.BrokerService.SubscribeOffers:output_type -> heint.Offer
	4, // 13: heint.BrokerService.RegisterNode:output_type -> heint.RegisterResponse
	4, // 14: heint.BrokerService.RegisterConsumer:output_type -> heint.RegisterResponse
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_greeter_proto_init() }
func file_proto_greeter_proto_init() {
	if File_proto_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greeter_proto_rawDesc), len(file_proto_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_greeter_proto_goTypes,
		DependencyIndexes: file_proto_greeter_proto_depIdxs,
		MessageInfos:      file_proto_greeter_proto_msgTypes,
	}.Build()
	File_proto_greeter_proto = out.File
	file_proto_greeter_proto_goTypes = nil
	file_proto_greeter_proto_depIdxs = nil
}
